#+TITLE: Omni Kill

[[https://travis-ci.org/AdrieanKhisbe/omni-kill.el][file:https://travis-ci.org/AdrieanKhisbe/omni-kill.el.svg]]
[[https://coveralls.io/r/AdrieanKhisbe/omni-kill.el][file:https://coveralls.io/repos/AdrieanKhisbe/omni-kill.el/badge.svg]]
[[http://melpa.org/#/omni-kill][file:http://melpa.org/packages/omni-kill-badge.svg]]
[[http://stable.melpa.org/#/omni-kill][file:http://stable.melpa.org/packages/omni-kill-badge.svg]]
[[https://github.com/AdrieanKhisbe/omni-kill.el/tags][file:https://img.shields.io/github/tag/AdrieanKhisbe/omni-kill.el.svg]]
[[http://www.gnu.org/licenses/gpl-3.0.html][http://img.shields.io/:license-gpl3-blue.svg]]

/Kill all the things! \o//

* Descriptlon

This /in early development/ library is there to assist emacs user to quickly copy, select, kill, ... things that are at point: emails, url, sentence...
It's built on top of =thingatpt=, and just provide wrapper functions.

* Usage

Once loaded you will have at you disposal many commands to grab, kill, delete, *“Things”* that are at point.
The naming scheme for these commands are by default =omni-ACTION-THING=, with:

- actions :: =copy, delete, select, kill=
- things :: =symbol list sexp defun filename url email word sentence whitespace line page= (aka the default =thingatpt=)

If you want to adapt or change the naming scheme, just run =M-x customization-group RET omni-kill=. You can also add to the list your custom =things=. By default you will get =omni-copy-url=, =omni-delete-line=, and so on.

Besides you can use the /dispatch/ functions. They take as argument the next key you type, and look on an alist to get the associated thing.
These are named =omni-ACTION=, and the char to thing association can be customized through the == custom.

For example calling =omni-kill= followed by the letter =e=, will kill the current =email= at point if any.


* Installation

To install it, install the package from =melpa= or just put the `omni-kill.el` in your load path, and require it.
Then bind the commands to the keybinding that suit you.

If you are using =use-package=, here is the config you could use.
#+begin_src emacs-lisp
  (use-package omni-kill
      :bind (("M-s c". omni-copy)
             ("M-s d". omni-delete)
             ("M-s k". omni-kill)
             ("M-s s". omni-select)))
#+end_src

* Notes

This is still a prototype. So if ever you think about using it, prefer the =master= branch, and expect to update your config.

Work is in progress so many extension are on the way, but I'll try to avoid incompatible change on he =master= branch
# §more

*If you have any remark, refactor suggestion or else, just pose an issue ;)*
